<a href="https://colab.research.google.com/github/RubenCarty/Deep-Learning/blob/main/LAB_01_HOLA_MUNDO_ML_CON_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **HOLA MUNDO DE MACHINE LEARNING CON DEEP LEARNING**

### [Msc Ruben Quispe](https://www.linkedin.com/in/ruben-quispe-l/)


In [ ]:
print('Hola mundo')

Hola mundo


In [ ]:
print ('BIENVENIDO A LA LA CLASE DE IA & SE')

BIENVENIDO A LA LA CLASE DE IA & SE


## ALGEBRA LINEAL

# 1. Escalar

Es simplemente un número unico

In [ ]:
x = 10
x

10

In [ ]:
x = 4
y = 5
z= 2*x

In [ ]:
z

8

In [ ]:
x+y

9

In [ ]:
x

4

# 2. Vector
Es una coleccion de números dispuestos en secuencia

\begin{equation}
    \mathbf{X} =
    \begin{bmatrix}x_1\\x_2\\...\\x_n\end{bmatrix}
\end{equation}

In [ ]:
# UN VECTOR
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
# primer valor
x[0]

np.int64(1)

In [ ]:
x[2]

np.int64(3)

In [ ]:
# ultimo valor
x[4]

IndexError: index 4 is out of bounds for axis 0 with size 3

# 3. Matrices
es un vector bidemencional, es un areglo rectangular
\begin{equation}
    \mathbf{A} =
    \begin{bmatrix}A_{1,1}&& A_{1,2} \\ A_{2,1}&& A_{2,2}\end{bmatrix}
\end{equation}





In [ ]:
# UNA MATRIZ
A = np.array([[1,2],[3,4]])
A


array([[1, 2],
       [3, 4]])

# 4. Tensor

In [ ]:
A = np.array([[[1, 2], [3, 4]],[[1, 2], [3, 4]]])
A

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

# CONTEXTO
Calcula  y cuando x = 20

* x = -1, 0,1,2,3,4,5
* y = -3,-1,1,3,5,7,9

y = 2x-1

# 1. IMPORTAR LAS LIBRERIAS NECESARIAS

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

# 2. Definir la arquitectura de nuestra red neuronal

In [ ]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='sgd', loss ='mean_squared_error')

# 3. Proporcionar datos

In [ ]:
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0,5.0, 6.0, 7.0, 8.0,9.0,10.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0,13.0,15.0,17.0,19.0 ], dtype=float)

# 4. Train y test de nuestra red nueronal

In [ ]:
model.fit(xs,ys, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - loss: 69.4684
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 8.6825
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 1.4854
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.6275
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 0.5194
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.5002
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.4916
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.4843
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.4773
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.4704
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.4636
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.4568
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.4502
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.4437
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.4373
Epoch 16/500
1/

In [ ]:
print(model.predict(np.array([[10.0]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
[[18.986975]]
